workflows:
  build-and-package:
    name: Build Debug APK and IPA
    environment:
      vars:
        FLUTTER_CHANNEL: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build Debug APK
        script: flutter build apk --debug

      - name: Build Debug IPA
        script: flutter build ios --debug --no-codesign
