name: north_star
description: a personal fitness app

publish_to: 'none'
version: 10.0.1+6

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  cupertino_icons: ^1.0.4
  get: ^4.6.5
#  intl: ^0.18.0
  intl: ^0.19.0
  uuid: ^4.1.0
  http: ^1.2.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_markdown: ^0.6.10+2
  syncfusion_flutter_gauges: ^27.1.58
  syncfusion_flutter_datepicker: ^27.1.58
  syncfusion_flutter_calendar: ^27.1.58
  table_calendar: ^3.0.6
  url_launcher: ^6.1.4
  permission_handler: ^11.0.0

  flutter_cupertino_date_picker_fork: ^1.0.7

  string_similarity: ^2.0.0
  flutter_typeahead: ^5.2.0
  flutter_datetime_picker_bdaya: ^3.0.1
  dio: ^5.0.3

  image_picker: ^1.0.4
  mobile_scanner: ^3.3.0 #For IOS
  # mobile_scanner: ^6.0.2 #For Android
  lottie: ^3.1.3
  step_progress_indicator: ^1.0.2
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.6.2
  country_currency_pickers: ^3.0.0
  simple_speed_dial: ^0.1.7
  photo_view: ^0.14.0
  marquee: ^2.2.3
  im_animations: ^0.1.2
  flutter_html: ^3.0.0-alpha.6
  file_picker: ^8.0.6

  provider: ^6.0.5
  flutter_svg: ^2.0.7
  wakelock_plus: ^1.1.1

  firebase_crashlytics: ^4.1.4
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5
  firebase_storage: ^12.3.5
  firebase_messaging: 15.1.4
  logger: ^2.0.2+1
#  agora_uikit: ^1.3.10
  pip_view: ^0.9.7
  
  pin_code_fields: ^8.0.1
  syncfusion_flutter_pdf: ^27.1.58
  open_file: ^3.3.2
  app_links: ^6.3.2
  flutter_cached_pdfview: ^0.4.2
  qr_flutter: ^4.1.0
  
  health: ^11.1.0
  intl_phone_field: ^3.2.0
  intl_phone_number_input: ^0.7.4
  typed_data: ^1.3.2
  share_plus: ^10.0.0
  carousel_slider_plus: ^7.0.1

  zego_uikit: ^2.27.14
  zego_uikit_signaling_plugin: ^2.8.5
  zego_uikit_prebuilt_call: ^4.16.8
  flutter_local_notifications: ^18.0.1
#  agora_rtc_engine: ^6.3.2
  syncfusion_flutter_charts: ^27.1.58
  pdf: ^3.11.1
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/cliparts/
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/item_backgrounds/
    - assets/icons/
    - assets/svgs/
    - assets/home/
    - assets/lotties/
    - assets/appicons/
    - assets/proItems/
  fonts:
    - family: IcoMoon
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: Bebas Neue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
