// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHHxZpKGgxNw_IfkSFXQB7FO6snpDpKcY',
    appId: '1:579973402915:android:235fe0b56f5cf4e7943c96',
    messagingSenderId: '579973402915',
    projectId: 'nsdev01',
    databaseURL: 'https://nsdev01-default-rtdb.firebaseio.com',
    storageBucket: 'nsdev01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfXg3fccZr1h979KmfwVH8UvsEOCY9Kac',
    appId: '1:579973402915:ios:0f8652939d7d2721943c96',
    messagingSenderId: '579973402915',
    projectId: 'nsdev01',
    databaseURL: 'https://nsdev01-default-rtdb.firebaseio.com',
    storageBucket: 'nsdev01.appspot.com',
    androidClientId: '579973402915-0ghhg512rcje4pi6u9mv66fkfonjf3ll.apps.googleusercontent.com',
    iosClientId: '579973402915-nou1dn1rron56h5h5a1531d3fabojl1h.apps.googleusercontent.com',
    iosBundleId: 'com.northstar.fitness',
  );
}
