name: Build and Email Android APK

on:
  push:
    branches: ["android"]
  pull_request:
    branches: ["android"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4" # Latest Flutter version
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --split-per-abi --target-platform android-arm64

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-arm64-v8a-release
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk

      - name: Send email with APK
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          subject: New Android Build Available
          body: Please find the latest Android build attached.
          to: teamipv404@gmail.com
          from: GitHub Actions
          attachments: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          secure: true
